QLNhaSach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ # what view connects to the url pattern
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),

    path('update_item/', views.updateItem, name='update_item'),
    path('customer_info/', views.customer_info, name='information'),

    
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),


    # path('user/', views.userPage, name='user-page'),

    # path('account/', views.accountSetting, name='account'),

    path('book/<str:pk>/', views.book_details, name='book'), # xem chi tiết sách
    # path('customer/<str:pk_test>', views.customer, name='customer'),

    path('book_entry/', views.book_entry, name='book_entry'),
    # path('create_book/<str:pk>', views.createBook, name='create_Book'),
    # path('update_book/<str:pk>', views.updateBook, name='update_Book'),
    # path('delete_book/<str:pk>', views.deleteBook, name='delete_Book'),

    path('review_invoice/<str:pk>/', views.reviewInvoice, name='review_invoice'),

    path('list_invoice/', views.listInvoice, name='list_invoice'),

    path('debt_report/', views.debt_report, name='debt_report'),
    path('inventory_report/', views.inventory_report, name='inventory_report'),
]

book/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.utils import timezone

# Create your models here.
class Person(models.Model):
    class Meta:
        verbose_name_plural = 'Thành viên'
        
    # list_chucvu = (
	# 		('nhân viên', 'nhân viên'),
	# 		('thủ kho', 'thủ kho'),
    #         ('chủ nhà sách', 'chủ nhà sách'),
    #         ('khách hàng', 'khách hàng')
	# 		) 
    id = models.CharField(max_length=100, primary_key=True, editable=True)
    ho_ten = models.CharField('Họ tên', max_length=100, null=True)
    ngay_sinh = models.DateField('Ngày sinh', null=True, editable=True)
    so_dien_thoai = models.CharField('Số điện thoại', max_length=13, null=True)
    dia_chi = models.CharField('Địa chỉ', max_length=1000, null=True)
    email = models.CharField('Email', max_length=50, null=True)
    # chuc_vu = models.CharField('Chức vụ', max_length=100, null=True, choices=list_chucvu)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE) # a user can have 1 customer, a customer have a user
    
    def __str__(self):
        return self.id

    @property
    def get_group_name(self):
        query_set = Group.objects.filter(user = self.user)
        if not query_set:
            query_set = ''
        else:
            query_set = query_set[0].name.capitalize()

        return query_set

    @property
    def get_debt(self):
        if 'kh' in self.id: 
            s = 0
            cac_hd = HoaDon.objects.filter(khach_hang=self)
            # print(cac_hd)
            for hd in cac_hd:
                if hd.tong_tien != hd.da_tra and hd.da_tra != -1:
                    s += hd.tong_tien - hd.da_tra
                    print(hd, s)
            return s


# class TheLoai(models.Model):
    
class Sach(models.Model):
    # id = models.CharField(max_length=100, primary_key=True) # PK: id và ngay_nhap
    ten_sach = models.CharField(max_length=100, null=True)
    # ngay_nhap = models.DateField(auto_now_add=True)
    ngay_nhap = models.DateField(null=True,default=timezone.now)
    so_luong = models.PositiveIntegerField(null=True)
    the_loai = models.CharField(max_length=100, null=True)
    tac_gia = models.CharField(max_length=100, null=True)
    don_gia = models.PositiveBigIntegerField(null=True)
    gia_ban = models.PositiveBigIntegerField(null=True)
    nha_xuat_ban = models.CharField(max_length=100, null=True)
    nam_xuat_ban = models.PositiveIntegerField(null=True)
    nguoi_nhap = models.ForeignKey(Person, null=True, on_delete=models.PROTECT) 
    anh_sach = models.ImageField(default="static/placeholder.png",null=True, blank=True)
    mo_ta = models.TextField("Mô tả ngắn", max_length=1000, null=True, blank=True)
    
    def __str__(self):
        return f'{self.ten_sach}_{self.ngay_nhap}'
    
    def get_absolute_url(self):
        return f"/book/{self.id}/" 
    
    # def clean(self):
    #     if self.nguoi_nhap.chuc_vu != 'thủ kho':
    #         raise ValidationError('người nhập phải là thủ kho!')

    @property
    def imageURL(self):
        try:
            url = self.anh_sach.url
        except:
            url = ''
        return url

    @property
    def get_book_quantity(self):
        return self.so_luong-20
    
    @property
    def get_name(self):
        return self.ten_sach
        
    class Meta: # vì django ko cho tạo PK 2 thuộc tính nên làm cách này
        unique_together = ('id', 'ngay_nhap',)
        verbose_name_plural = "Sách"

class HoaDon(models.Model):
    class Meta:
        verbose_name_plural = 'Hóa đơn'
        
    pttt = (
            ('Thẻ ngân hàng', 'Thẻ ngân hàng'),
            ('Tiền mặt', 'Tiền mặt'),
            )
    id_HD = models.CharField('Mã hóa đơn', max_length=100, primary_key=True, default= 'HD_', editable=True)
    ngay_lap_HD = models.DateTimeField(null=True)
    tong_tien = models.FloatField(null=True, default=0, editable=True)
    nguoi_lap_HD = models.ForeignKey(Person, verbose_name='Nhân viên', null=True, blank=True, related_name="nhan_vien", on_delete=models.PROTECT)
    khach_hang = models.ForeignKey(Person, verbose_name='Khách hàng', null=True, blank=True, related_name="khach_hang", on_delete=models.PROTECT)
    phuong_thuc_thanh_toan = models.CharField('Phương thức thanh toán', max_length=100, null=False, choices=pttt)
    da_tra = models.FloatField(null=True, default=0, editable=True)
    
    def __str__(self):
        return self.id_HD
    
    def clean(self):
        # constraint: khách hàng phải có chuc_vu='khách hàng'
        # if self.khach_hang.chuc_vu != 'khách hàng':
        #     raise ValidationError('nhân viên không hợp lệ')
        # constraint: người lập HD phải là nhân viên
        # if self.nguoi_lap_HD.chuc_vu != 'nhân viên':
        #     raise ValidationError('người lập hóa đơn phải là nhân viên!')
        # constraint: chỉ nợ tối đa 20.000d
        if self.tong_tien is not None and self.da_tra is not None and self.tong_tien - self.da_tra > 20000:
            raise ValidationError('khách hàng chỉ được phép nợ tối đa 20.000d')


    @property 
    def get_cart_total(self):
        cac_mat_hang = self.chitiethoadon_set.all()
        tong_tien = sum([mh.get_total for mh in cac_mat_hang])
        return tong_tien

    @property
    def get_cart_items(self):
        cac_mat_hang = self.chitiethoadon_set.all()
        total = sum([mh.so_luong for mh in cac_mat_hang])
        return total

class ChiTietHoaDon(models.Model): # 1 lần nhập 1 sách
    # cthd của hóa đơn nào
    hoa_don = models.ForeignKey(HoaDon, verbose_name='Hóa đơn', on_delete=models.PROTECT)
    # khach_hang = models.ForeignKey(Person, verbose_name='Khách hàng', on_delete=models.PROTECT)
    sach = models.ForeignKey(Sach, verbose_name='Sản phẩm', on_delete=models.PROTECT)
    so_luong = models.PositiveIntegerField(null=True, default=0, editable=True)
    # giá bán 1 sản phẩm
    # gia_ban = models.FloatField(null=True)
    
    def __str__(self):
        return self.hoa_don.id_HD

    # def clean(self):
    #     # constraint: sách sau khi bán vẫn còn ít nhất 20 cuốn trong kho Sach   
    @property
    def get_total(self):
        total = self.sach.gia_ban * self.so_luong
        return total

    class Meta:
        verbose_name_plural = 'Chi tiết hóa đơn'

# util model để support hàm debt_report() trong view, phải database chính thức
class Debt(models.Model):
    khach_hang = models.ForeignKey(Person, null=True, blank=True, on_delete=models.PROTECT)
    no_dau = models.FloatField(null=True)
    phat_sinh = models.FloatField(null=True)
    
    @property
    def no_cuoi(self): return self.no_dau + self.phat_sinh

book/forms.py
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm, Textarea

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomerInfo(ModelForm):
    class Meta:
        model = Person
        fields = ['ho_ten', 'so_dien_thoai', 'email', 'profile_pic']

class InvoiceForm(ModelForm):
    class Meta:
        model = HoaDon
        fields = ['id_HD', 'ngay_lap_HD']



class CreateBook(ModelForm):
    class Meta:
        model = Sach
        fields = ['ten_sach', 'ngay_nhap', 'so_luong', 'the_loai', 'tac_gia', 'don_gia', 'gia_ban', 'nha_xuat_ban', 'nam_xuat_ban', 'anh_sach', 'mo_ta']

book/templates/book/book_entry.html
{% extends 'book/main.html' %}
{% load static %}
{% load humanize %}
{% block title %}Nhập sách{% endblock %}

{% block content %}
<!-- <style>
 .cl_ten_sach{
   width: 700px;
   background-color: rgb(255, 255, 255);
   position: relative;
   left: 120px;
   top: 10px;
   height: 40px;
   border-radius: 20px solid black ;
 }
 #id_ten_sach{
  width: 690px;
  height: 40px;
 }
  form{
    text-align: center;
    background-color: yellow;
  }
</style> -->
<form autocomplete="off" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div><p>Nhập sách mới</p></div>
  <hr>
  <div style="flex:2"><strong>Tên sách</strong></div>
    <div class="cl_ten_sach">
      {{form.ten_sach}}
    </div>


  <div style="flex:2"><strong>Ngày nhập</strong></div>
  {{form.ngay_nhap}}
  <br>

  <div style="flex:2"><strong>Số lượng</strong></div>
  {{form.so_luong}}
  <br>

  <div style="flex:2"><strong>Thể loại</strong></div>
  {{form.the_loai}}
  <br>

  <div style="flex:2"><strong>Tác giả</strong></div>
  {{form.tac_gia}}
  <br>

  <div style="flex:2"><strong>Đơn giá</strong></div>
  {{form.don_gia}}
  <br>

  <div style="flex:2"><strong>Giá bán</strong></div>
  {{form.gia_ban}}
  <br>

  <div style="flex:2"><strong>Nhà xuất bản</strong></div>
  {{form.nha_xuat_ban}}
  <br>

  <div style="flex:2"><strong>Năm xuất bản</strong></div>
  {{form.nam_xuat_ban}}
  <br>

  <div style="flex:2"><strong>Mô tả</strong></div>
  {{form.mo_ta}}
  <br>

  <div style="flex:2"><strong>Ảnh sách</strong></div>
  {{form.anh_sach}}
  <br>
  <div class="submit">
    <input class="btn" type="submit">
  </div>
</form>

<script>
  function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
    the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function (e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false; }
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function (e) {
            /*insert the value for the autocomplete text field:*/
            inp.value = this.getElementsByTagName("input")[0].value;
            /*close the list of autocompleted values,
            (or any other open lists of autocompleted values:*/
            closeAllLists();
          });
          a.appendChild(b);
        }
      }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function (e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
    });
    function addActive(x) {
      /*a function to classify an item as "active":*/
      if (!x) return false;
      /*start by removing the "active" class on all items:*/
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      /*add class "autocomplete-active":*/
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      /*a function to remove the "active" class from all autocomplete items:*/
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }
    function closeAllLists(elmnt) {
      /*close all autocomplete lists in the document,
      except the one passed as an argument:*/
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
          x[i].parentNode.removeChild(x[i]);
        }
      }
    }
    /*execute a function when someone clicks in the document:*/
    document.addEventListener("click", function (e) {
      closeAllLists(e.target);
    });
  }

  /*An array containing all the country names in the world:*/
  var Tensach = [{% for s in sach %}'{{s.ten_sach}}', {% endfor %}]
  /*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
  autocomplete(document.getElementById("id_ten_sach"), Tensach);
  var input = document.getElementById('id_ten_sach');
  var onChange = function (evt) {
    var ten = this.value;
    {% for s in sach %}
    var temp = '{{s.ten_sach}}'
    if (temp == ten) {
      document.getElementById('id_ngay_nhap').value = '{{s.ngay_nhap.day}}/{{s.ngay_nhap.month}}/{{s.ngay_nhap.year}}'
      document.getElementById('id_the_loai').value = '{{s.the_loai}}'
      document.getElementById('id_tac_gia').value = '{{s.tac_gia}}'
      document.getElementById('id_don_gia').value = '{{s.don_gia}}'
      document.getElementById('id_gia_ban').value = '{{s.gia_ban}}'
      document.getElementById('id_nha_xuat_ban').value = '{{s.nha_xuat_ban}}'
      document.getElementById('id_nam_xuat_ban').value = '{{s.nam_xuat_ban}}'
      document.getElementById('id_mo_ta').value = '{{s.mo_ta}}'
      console.log('{{s.anh_sach}}')
    }
    {% endfor %}

  };
  input.addEventListener('input', onChange, false);


</script>

{% endblock %}

book/templates/book/book_form.html
{%  extends 'book/main.html' %}
{% load static %}
<!-- Tạo một sách mới -->
{% block title %}Sách{% endblock %}

{% block content %}

{% endblock %}

book/templates/book/cart.html
{% extends 'book/main.html' %}
{% load static %}
{% load humanize %}
{% block title %}Giỏ hàng{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Tên sách</strong></div>
                <div style="flex:1"><strong>Giá bán</strong></div>
                <div style="flex:1"><strong>Số lượng</strong></div>
                <div style="flex:1"><strong>Giá tiền</strong></div>
                <div style="flex:1"></div>
            </div>
            
            {% for mh in mat_hang %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" style="width: 190px; height: 248px" src="{{mh.sach.imageURL}}"></div>
                <div style="flex:2">{{mh.sach.ten_sach}}</div>
                <div style="flex:1">{{mh.sach.gia_ban|floatformat:0|intcomma}} VND</div>

                <div style="flex:1">
                    <p class="quantity">{{mh.so_luong}}</p>
                    <div class="quantity">
                        <img data-book={{mh.sach.id}} data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
                
                        <img data-book={{mh.sach.id}} data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1">{{mh.get_total|floatformat:0|intcomma}} VND</div>

                <div style="flex:1">
                    <img data-book={{mh.sach.id}} data-action="clear" class="chg-quantity update-cart" src="{% static  'images/remove.png' %}" style="width:12px; height:12px">
                </div>
            </div>
            {% endfor %}
        </div>
        <br>
        <br>
        <div class="box-element">
            <a  class="btn btn-outline-dark" href="{% url 'home' %}">&#x2190; Tiếp tục mua sách</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>SL: <strong>{{hd.get_cart_items}}</strong></h5></th>
                    <th><h5>Tổng tiền:<strong> {{hd.get_cart_total|floatformat:0|intcomma}} VND</strong></h5></th>
                    <th>
                        <a  style="float:right; margin:5px;" class="btn btn-warning" href="{% url 'checkout' %}">Thanh toán</a>

                    </th>
                </tr>
            </table>
        </div>

    </div>
</div>
{% endblock %}

book/templates/book/checkout.html
{% extends 'book/main.html' %}
{% load static %}
{% load humanize %}
{% block title %}Mua hàng{% endblock %}
{% block content %}
<div>
    <div class="box-element" id="form-wrapper">
        <form id="form">
            <div class="form-row">
                <div class="col-md-8 mb-3">
                    <label for="name">Khách hàng</label>
                    <input required class="form-control" type="text" name="name" id="customer-name" value="{{request.user.person.ho_ten}}">
                </div>
                <div class="col-md-4 mb-3">
                    <label for="sdt">SĐT</label>
                    <input required class="form-control" type="text" name="sdt" value="{{request.user.person.so_dien_thoai}}">
                </div>
            </div> 
            <br>
            <h5><strong>Địa chỉ nhận hàng</strong></h5>
            <div class="col-md-12 mb-3">
                <label for="address"></label>
                <input class="form-control" type="text" name="address" value="{{request.user.person.dia_chi}}">
            </div>

            <!-- <div class="form-row" id="shipping-info">  
                <div class="col-md-4 mb-3">
                    <label for="province-city">Tỉnh/Thành phố</label>
                    <input required class="form-control" type="text" name="province-city" placeholder="TP Hồ Chí Minh">
                </div>
                <div class="col-md-4 mb-3">
                    <label for="district">Quận/Huyện</label>
                    <input class="form-control" type="text" name="district" placeholder="Quận 1">
                </div>
                <div class="col-md-4 mb-3">
                    <label for="address">Địa chỉ cụ thể</label>
                    <input class="form-control" type="text" name="address" placeholder="Số nhà, tên đường, phường">
                </div>
            </div> -->

            <input id="form-button" class="btn btn-success btn-block" type="submit" value="Xác nhận">
        </form>
    </div>

    <br>
    <div class="box-element hidden" id="payment-info">Phương thức thanh toán
        <select id="payment-option" name="payment-option">
            <option value="none">--Chọn phương thức thanh toán--</option>
            <option value="the-ngan-hang">Thẻ ngân hàng</option>
            <option value="tien-mat">Tiền mặt</option>
        </select>
        <hr>
        <div class="hidden" id="payment-cash">
            <div class="col-md-12 mb-3 mt-2">
                <label for="pay">Số tiền trả</label>
                <input class="form-control" type="text" name="pay" id="pay" placeholder="{{hd.get_cart_total}}">
            </div>
        </div>
        <button id="payment" class="btn btn-warning hidden">Thanh toán</button>
    </div>
    <br>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}

        <input type="submit" name="Thanh toán">
    </form>
    
    <br>
    <br>
    <div class="box-element">
        <div class="box-element">
            <a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Trở lại giỏ</a>
            <hr>
            <h3>Đơn hàng</h3>
            <h5>SL: {{hd.get_cart_items}}</h5>
            <h5>Tổng tiền: {{hd.get_cart_total|floatformat:0|intcomma}} VND</h5>

            <hr>
            {% for mh in mat_hang %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{mh.sach.imageURL}}"></div>
                <div style="flex:2">{{mh.sach.ten_sach}}</div>
                <div style="flex:1">{{mh.sach.gia_ban|floatformat:0|intcomma}} VND</div>
                <div style="flex:1">{{mh.so_luong}}</div>
            </div>
            {% endfor %}
            

        </div>
    </div>
</div>

<script type="text/javascript">
    // var total = '{{order.get_cart_total|floatformat:0}}'
    var form = document.getElementById('form')

    form.addEventListener('submit', function(e){
        e.preventDefault()
        document.getElementById('form-button').classList.add("hidden")
        document.getElementById('payment-info').classList.remove("hidden")

    })
    document.getElementById('payment-option').addEventListener('click', function(e){
        selectPaymentOption()})

    function selectPaymentOption(){
        let selector = document.getElementById("payment-option"); 

            selector.addEventListener("change", () => {
                switch (selector.value) {
                    case "the-ngan-hang":
                        document.getElementById('payment-cash').classList.add("hidden");
                        document.getElementById('payment').classList.remove("hidden");
                        break; 
                    case "tien-mat":
                        document.getElementById('payment-cash').classList.remove("hidden");
                        document.getElementById('payment').classList.remove("hidden");
                        break;
                    case 'none':
                        document.getElementById('payment').classList.add("hidden");
                        document.getElementById('payment-cash').classList.add("hidden");
                        break;
                }
            });
    }

    document.getElementById('payment').addEventListener('click', function(){
        alert('Đã thanh toán');

        window.location.href = "{% url 'home' %}"
    })

    function submitFormData(){

        // lấy thông tin từ form, ví dụ
        shippingInfo.address = form.address.value

        // url của html muốn truyền post tới, theo video đã gửi trên group
        var url= '/process_order/'

        // câu lệnh fetch
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body:JSON.stringify({'shipping': shippingInfo}) // truyền thông data muốn gửi 
        })

        .then((response) => response.json()) 

        .then((data) => {
            console.log('Success: ', data); // send data thành công, xong

            // clear cart, có thể bị lỗi vì mình làm hơi khác
            // cart = {}
            // document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/'

            window.location.href = "{% url 'home' %}" // chuyển hướng về home
        })
    }
</script>

{% endblock %}

book/templates/book/debt_report.html
{%  extends 'book/main.html' %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="page-content container">
    <div class="page-header text-blue-d2">
        <h1 class="page-title text-secondary-d1">
            Báo cáo nợ của khách hàng
        </h1>
        <label for="month-select">Chọn tháng và năm:</label>

        <form role="form" method='post' action=''>
            <tr>
             {% csrf_token %}

                <td><select name="month" value="5">
                   <option value="1">1</option>
                   <option value="2">2</option>
                   <option value="3">3</option>
                   <option value="4">4</option>
                   <option value="5" selected>5</option>
                   <option value="6">6</option>
                   <option value="7">7</option>
                   <option value="8">8</option>
                   <option value="9">9</option>
                   <option value="10">10</option>
                   <option value="11">11</option>
                   <option value="12">12</option>
                </select></td>

                <td><select name="year">
                   <option value="2019">2019</option>
                   <option value="2020">2020</option>
                   <option value="2020">2021</option>
                   <option value="2021" selected>2022</option>
                </select></td>
           <td>
           <input type='submit' value='search' />
           </td>
           </tr>
           </form>
        {% comment %} <div class="page-tools">
            <div class="action-buttons">
                <a class="btn bg-white btn-light mx-1px text-95" href="#" data-title="Print">
                    <i class=""></i>
                </a>
                <a class="btn bg-white btn-light mx-1px text-95" href="#" data-title="PDF">
                    <i class=""></i>
                </a>
            </div>
        </div>
    </div> {% endcomment %}


<div class="table-responsive">
    <table class="table table-striped table-borderless border-0 border-b-2 brc-default-l1">
        <thead class="bg-none bgc-default-tp1">
            <tr class="text-black">
                {% comment %} <th>ID_HoaDon</th> {% endcomment %}
                <th>Khách hàng</th>
                <th>Nợ đầu</th>
                <th>Phát sinh</th>
                <th>Nợ cuối</th>
                
            </tr>
        </thead>

        <tbody class="text-95 text-secondary-d3">
            {% for debt in list_debt %}
            <tr></tr>
            <tr>
                {% comment %} <td>{{debt.id_HD}}</td> {% endcomment %}
                <td>{{debt.khach_hang.ho_ten}}</td>
                
                {% load subtract %}
                <td>{{debt.no_dau}}</td>

                <td>{{debt.phat_sinh}}</td>
                <td>{{debt.no_cuoi}}</td>
                {% comment %} <th><a class="btn btn-sm btn-info" href="{% url 'review_invoice' invoice.id_HD %}">Xem</a></th> {% endcomment %}
            </tr> 
            {% endfor %}
            
    </table>
</div>


{% endblock content %}

book/templates/book/delete_book.html
{%  extends 'book/main.html' %}
{% load static %}

<!-- confirm xóa một cuốn sách -->
{% block title %}Xóa sách{% endblock %}

{% block content %}
    <!-- <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body">
                <p>Are you sure you want to delete {{item}}</p>

                <form action="{% url 'delete_order' item.id %}" method="POST">
                    {% csrf_token %}
                    <a class="btn btn-warning" href="{% url 'home' %}">Cancel</a>
                    <input class="btn btn-danger" type="submit" name="Confirm">
                </form> 
            </div>
        </div>
    </div> -->
    
{% endblock %}